//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementDataModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentPackage
    {
        public System.Guid Guid { get; set; }
        public int Type { get; set; }
        public string KeyName { get; set; }
        public string Title { get; set; }
        public decimal BasePrice { get; set; }
        public decimal BaseLicensePrice { get; set; }
        public decimal ServicePrice { get; set; }
        public bool IsServiceByLicense { get; set; }
        public int TryDays { get; set; }
        public string Description { get; set; }
        public System.Guid msrepl_tran_version { get; set; }
    
        public virtual Agent Agent { get; set; }
    }
}
