//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementDataModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agent()
        {
            this.AgentBankAccounts = new HashSet<AgentBankAccount>();
            this.AgentBusinesses = new HashSet<AgentBusiness>();
            this.AgentBusinessMoneyNotes = new HashSet<AgentBusinessMoneyNote>();
            this.AgentLogs = new HashSet<AgentLog>();
            this.AgentMoneyNotes = new HashSet<AgentMoneyNote>();
            this.AgentPackages = new HashSet<AgentPackage>();
            this.AgentParameters = new HashSet<AgentParameter>();
            this.AgentUsers = new HashSet<AgentUser>();
        }
    
        public System.Guid Guid { get; set; }
        public System.Guid AgentGroupGuid { get; set; }
        public string Account { get; set; }
        public string Password { get; set; }
        public string Company { get; set; }
        public string LinkMan { get; set; }
        public string Tel { get; set; }
        public int ProvinceId { get; set; }
        public int CityId { get; set; }
        public int CountyId { get; set; }
        public string Address { get; set; }
        public string Postcode { get; set; }
        public string BusinessArea { get; set; }
        public Nullable<System.DateTime> RegisterTime { get; set; }
        public string Meno { get; set; }
        public decimal TotalMoney { get; set; }
        public decimal AvailableMoney { get; set; }
        public decimal TotalGiftMoney { get; set; }
        public decimal AvailableGiftMoney { get; set; }
        public int TotalAuthNum { get; set; }
        public int AvailableAuthNum { get; set; }
        public int TotalSms { get; set; }
        public int AvailableSms { get; set; }
        public int TotalMms { get; set; }
        public int AvailableMms { get; set; }
        public Nullable<System.Guid> ChannelPackageGuid { get; set; }
        public int SmsPriority { get; set; }
        public string SingleMobileSmsChannel { get; set; }
        public string SingleUnicomSmsChannel { get; set; }
        public string SingleTelecomSmsChannel { get; set; }
        public string MultipleMobileSmsChannel { get; set; }
        public string MultipleUnicomSmsChannel { get; set; }
        public string MultipleTelecomSmsChannel { get; set; }
        public string SingleMmsKeyName { get; set; }
        public string MultiMmsKeyName { get; set; }
        public bool IsLocked { get; set; }
        public string LogoName { get; set; }
        public string WebAddress { get; set; }
        public string TelecomDomain { get; set; }
        public string NetcomDomain { get; set; }
        public string LoginSkin { get; set; }
        public string DomainLicense { get; set; }
        public string EPosLaunchLogo { get; set; }
        public string EPosLoginLogo { get; set; }
        public string SmsSignature { get; set; }
        public string LogoName2 { get; set; }
        public bool IsOwnChannel { get; set; }
        public System.Guid msrepl_tran_version { get; set; }
        public bool IsRefund { get; set; }
        public int Property { get; set; }
        public string PropertyName { get; set; }
        public string Copyright { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgentBankAccount> AgentBankAccounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgentBusiness> AgentBusinesses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgentBusinessMoneyNote> AgentBusinessMoneyNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgentLog> AgentLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgentMoneyNote> AgentMoneyNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgentPackage> AgentPackages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgentParameter> AgentParameters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgentUser> AgentUsers { get; set; }
    }
}
