//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementDataModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppPlatform
    {
        public System.Guid Guid { get; set; }
        public System.Guid ApplicationGuid { get; set; }
        public int TermPlatform { get; set; }
        public string Version { get; set; }
        public string DownloadAddress { get; set; }
        public string PushProvider { get; set; }
        public string AppParams { get; set; }
        public System.Guid msrepl_tran_version { get; set; }
    }
}
