//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementDataModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessBlockKeeper
    {
        public System.Guid Guid { get; set; }
        public byte[] SID { get; set; }
        public long BID { get; set; }
        public string BlockDomain { get; set; }
        public string BlockAction { get; set; }
        public string ParamsValue { get; set; }
        public string ResultsValue { get; set; }
        public int BlockStatus { get; set; }
    }
}
