//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementDataModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChannelRule
    {
        public System.Guid Guid { get; set; }
        public string ChannelKeyName { get; set; }
        public int SendMode { get; set; }
        public int OperatorType { get; set; }
        public Nullable<System.Guid> AgentGuid { get; set; }
        public byte[] SID { get; set; }
        public Nullable<int> SystemType { get; set; }
        public Nullable<int> AccountType { get; set; }
        public Nullable<int> SignedType { get; set; }
        public Nullable<int> LimitedValue { get; set; }
        public int Priority { get; set; }
        public bool Status { get; set; }
    }
}
