//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementDataModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChannelPackage
    {
        public System.Guid Guid { get; set; }
        public string PackageName { get; set; }
        public string SingleMobileSmsChannel { get; set; }
        public string SingleUnicomSmsChannel { get; set; }
        public string SingleTelecomSmsChannel { get; set; }
        public string MultipleMobileSmsChannel { get; set; }
        public string MultipleUnicomSmsChannel { get; set; }
        public string MultipleTelecomSmsChannel { get; set; }
        public string SingleMmsChannel { get; set; }
        public string MultipleMmsChannel { get; set; }
        public bool IsSystemDefault { get; set; }
        public int Priority { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string Meno { get; set; }
        public System.Guid msrepl_tran_version { get; set; }
    }
}
