//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementDataModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Channel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Channel()
        {
            this.SmsReceives = new HashSet<SmsReceive>();
        }
    
        public System.Guid Guid { get; set; }
        public string KeyName { get; set; }
        public string ChannelName { get; set; }
        public string Supplier { get; set; }
        public string Tel { get; set; }
        public int UsableCount { get; set; }
        public int LimitedValue { get; set; }
        public int SignLength { get; set; }
        public int OperatorType { get; set; }
        public string OperatorTypeName { get; set; }
        public int ChannelProperty { get; set; }
        public string ChannelPropertyName { get; set; }
        public string ChannelProviderClass { get; set; }
        public string ChannelParameters { get; set; }
        public int ChannelType { get; set; }
        public Nullable<System.Guid> RelationGuid { get; set; }
        public string SmsSignature { get; set; }
        public bool IsLocked { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string Meno { get; set; }
        public System.Guid msrepl_tran_version { get; set; }
        public System.DateTime StartInterval { get; set; }
        public System.DateTime EndInterval { get; set; }
        public string StandbyChannelKeyname { get; set; }
    
        public virtual ChannelQueue ChannelQueue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SmsReceive> SmsReceives { get; set; }
    }
}
