//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementDataModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckPayment
    {
        public System.Guid Guid { get; set; }
        public byte[] SID { get; set; }
        public string Title { get; set; }
        public string ApplyInfo { get; set; }
        public string FileGuids { get; set; }
        public int State { get; set; }
        public string Remark { get; set; }
        public System.DateTime ApplyTime { get; set; }
        public Nullable<System.DateTime> CheckTime { get; set; }
        public string CheckPerson { get; set; }
    }
}
