//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementDataModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hardware
    {
        public System.Guid Guid { get; set; }
        public string HardwareNo { get; set; }
        public string HardwareName { get; set; }
        public string Supplier { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public decimal SellPrice { get; set; }
        public int State { get; set; }
        public string Remark { get; set; }
        public System.Guid msrepl_tran_version { get; set; }
    }
}
