//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementDataModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public System.Guid Guid { get; set; }
        public string Fpqqlsh { get; set; }
        public bool Kplx { get; set; }
        public bool Fplx { get; set; }
        public string Xsfnsesbh { get; set; }
        public string Xsfmc { get; set; }
        public string Xsfdzdh { get; set; }
        public string Xsfyhzh { get; set; }
        public string Gmfnsrsbh { get; set; }
        public string Gmfmc { get; set; }
        public string Gmfdzdh { get; set; }
        public string Gmfyhzh { get; set; }
        public string Kpr { get; set; }
        public string Fpdm { get; set; }
        public string Fphm { get; set; }
        public decimal Jshj { get; set; }
        public decimal Hjje { get; set; }
        public decimal Hjse { get; set; }
        public bool Hylx { get; set; }
        public string Jym { get; set; }
        public string Pdfurl { get; set; }
    }
}
