//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementDataModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceItem
    {
        public System.Guid Guid { get; set; }
        public System.Guid InvoiceGuid { get; set; }
        public int Fphxz { get; set; }
        public string Xmmc { get; set; }
        public string Dw { get; set; }
        public string Ggxh { get; set; }
        public int Xmsl { get; set; }
        public decimal Xmdj { get; set; }
        public decimal Xmje { get; set; }
        public decimal Sl { get; set; }
        public decimal Se { get; set; }
    }
}
