//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementDataModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceRecord
    {
        public System.Guid Guid { get; set; }
        public byte[] SID { get; set; }
        public Nullable<System.Guid> AgentGuid { get; set; }
        public System.Guid InvoiceGuid { get; set; }
        public string SalerAccount { get; set; }
        public string FinanceAccount { get; set; }
        public string InvoiceItem { get; set; }
        public decimal TotalMoney { get; set; }
        public int State { get; set; }
        public System.DateTime CteateTime { get; set; }
        public Nullable<System.DateTime> CompleteTime { get; set; }
        public string ContractId { get; set; }
        public string Businesslicense { get; set; }
        public string Meno { get; set; }
    }
}
