//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementDataModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPDatabase
    {
        public System.Guid Guid { get; set; }
        public string Ip { get; set; }
        public string CountryId { get; set; }
        public string Country { get; set; }
        public int AreaId { get; set; }
        public string Area { get; set; }
        public int RegionId { get; set; }
        public string Region { get; set; }
        public int CityId { get; set; }
        public string City { get; set; }
        public int IspId { get; set; }
        public string Isp { get; set; }
        public string LatLng { get; set; }
    }
}
