//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementDataModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Member()
        {
            this.MicroBlogSettings = new HashSet<MicroBlogSetting>();
            this.MobileMemberCards = new HashSet<MobileMemberCard>();
            this.WeiXinMappings = new HashSet<WeiXinMapping>();
        }
    
        public System.Guid Guid { get; set; }
        public string Mobile { get; set; }
        public string TermIdentity { get; set; }
        public string WeixinId { get; set; }
        public string PassbookTicket { get; set; }
        public string TrueName { get; set; }
        public string Password { get; set; }
        public Nullable<int> Sex { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<bool> IsLunar { get; set; }
        public string MemberPhoto { get; set; }
        public Nullable<int> ProvinceId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> CountyId { get; set; }
        public string Address { get; set; }
        public string EMail { get; set; }
        public Nullable<System.DateTime> RegisterTime { get; set; }
        public string Meno { get; set; }
        public System.Guid msrepl_tran_version { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MicroBlogSetting> MicroBlogSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MobileMemberCard> MobileMemberCards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WeiXinMapping> WeiXinMappings { get; set; }
    }
}
