//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementDataModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MobileArea
    {
        public System.Guid Guid { get; set; }
        public string MobilePrefix { get; set; }
        public Nullable<int> ProvinceId { get; set; }
        public string Province { get; set; }
        public Nullable<int> CityId { get; set; }
        public string City { get; set; }
        public string AreaCode { get; set; }
        public string PostCode { get; set; }
        public string MobileType { get; set; }
        public System.Guid msrepl_tran_version { get; set; }
    }
}
