//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementDataModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MobileDevice
    {
        public System.Guid Guid { get; set; }
        public string DeviceId { get; set; }
        public string MessageTicket { get; set; }
        public int DeviceType { get; set; }
        public string DeviceInfo { get; set; }
        public int Status { get; set; }
        public System.DateTime LastLoginTime { get; set; }
        public string Version { get; set; }
        public Nullable<System.DateTime> LoginTime { get; set; }
        public System.Guid msrepl_tran_version { get; set; }
    }
}
