//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementDataModel.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ManagementEntities : DbContext
    {
        public ManagementEntities()
            : base("name=ManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agent> Agents { get; set; }
        public virtual DbSet<AgentBankAccount> AgentBankAccounts { get; set; }
        public virtual DbSet<AgentBusiness> AgentBusinesses { get; set; }
        public virtual DbSet<AgentBusinessMoneyNote> AgentBusinessMoneyNotes { get; set; }
        public virtual DbSet<AgentGroup> AgentGroups { get; set; }
        public virtual DbSet<AgentLog> AgentLogs { get; set; }
        public virtual DbSet<AgentMoneyNote> AgentMoneyNotes { get; set; }
        public virtual DbSet<AgentPackage> AgentPackages { get; set; }
        public virtual DbSet<AgentParameter> AgentParameters { get; set; }
        public virtual DbSet<AgentUser> AgentUsers { get; set; }
        public virtual DbSet<AgentUserBusiness> AgentUserBusinesses { get; set; }
        public virtual DbSet<AgentUserGroup> AgentUserGroups { get; set; }
        public virtual DbSet<AlipayParameter> AlipayParameters { get; set; }
        public virtual DbSet<AndroidPosInfo> AndroidPosInfoes { get; set; }
        public virtual DbSet<Answer> Answers { get; set; }
        public virtual DbSet<Application> Applications { get; set; }
        public virtual DbSet<AppMapping> AppMappings { get; set; }
        public virtual DbSet<AppPlatform> AppPlatforms { get; set; }
        public virtual DbSet<AppTerminal> AppTerminals { get; set; }
        public virtual DbSet<BankAccount> BankAccounts { get; set; }
        public virtual DbSet<BugInfo> BugInfoes { get; set; }
        public virtual DbSet<Bulletin> Bulletins { get; set; }
        public virtual DbSet<Business> Businesses { get; set; }
        public virtual DbSet<BusinessBlockKeeper> BusinessBlockKeepers { get; set; }
        public virtual DbSet<BusinessInterface> BusinessInterfaces { get; set; }
        public virtual DbSet<BusinessMoneyNote> BusinessMoneyNotes { get; set; }
        public virtual DbSet<BusinessParameter> BusinessParameters { get; set; }
        public virtual DbSet<CardNote> CardNotes { get; set; }
        public virtual DbSet<Channel> Channels { get; set; }
        public virtual DbSet<ChannelPackage> ChannelPackages { get; set; }
        public virtual DbSet<ChannelQueue> ChannelQueues { get; set; }
        public virtual DbSet<ChannelRule> ChannelRules { get; set; }
        public virtual DbSet<CheckPayment> CheckPayments { get; set; }
        public virtual DbSet<Edition> Editions { get; set; }
        public virtual DbSet<EditionPackage> EditionPackages { get; set; }
        public virtual DbSet<FileManagement> FileManagements { get; set; }
        public virtual DbSet<Hardware> Hardwares { get; set; }
        public virtual DbSet<Help> Helps { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<InvoiceItem> InvoiceItems { get; set; }
        public virtual DbSet<InvoiceOperation> InvoiceOperations { get; set; }
        public virtual DbSet<InvoiceRecord> InvoiceRecords { get; set; }
        public virtual DbSet<IPDatabase> IPDatabases { get; set; }
        public virtual DbSet<LockedParameter> LockedParameters { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<MemberLog> MemberLogs { get; set; }
        public virtual DbSet<MicroBlogSetting> MicroBlogSettings { get; set; }
        public virtual DbSet<MmsSend> MmsSends { get; set; }
        public virtual DbSet<MobileArea> MobileAreas { get; set; }
        public virtual DbSet<MobileCheckCode> MobileCheckCodes { get; set; }
        public virtual DbSet<MobileDevice> MobileDevices { get; set; }
        public virtual DbSet<MobileMemberCard> MobileMemberCards { get; set; }
        public virtual DbSet<MobileMessage> MobileMessages { get; set; }
        public virtual DbSet<MobileMessageFilter> MobileMessageFilters { get; set; }
        public virtual DbSet<MobileMessageSend> MobileMessageSends { get; set; }
        public virtual DbSet<MobileUpdateNote> MobileUpdateNotes { get; set; }
        public virtual DbSet<MobileUpdateSet> MobileUpdateSets { get; set; }
        public virtual DbSet<OemParameter> OemParameters { get; set; }
        public virtual DbSet<OnlineUser> OnlineUsers { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Package> Packages { get; set; }
        public virtual DbSet<Parameter> Parameters { get; set; }
        public virtual DbSet<ParameterMetadata> ParameterMetadatas { get; set; }
        public virtual DbSet<PlatformBug> PlatformBugs { get; set; }
        public virtual DbSet<PosConfiguration> PosConfigurations { get; set; }
        public virtual DbSet<PriceMode> PriceModes { get; set; }
        public virtual DbSet<PurchaseNote> PurchaseNotes { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<RecommendNote> RecommendNotes { get; set; }
        public virtual DbSet<ShortUrlMapping> ShortUrlMappings { get; set; }
        public virtual DbSet<SmsBlackList> SmsBlackLists { get; set; }
        public virtual DbSet<SmsDeadNumber> SmsDeadNumbers { get; set; }
        public virtual DbSet<SmsReceive> SmsReceives { get; set; }
        public virtual DbSet<SmsRegRecord> SmsRegRecords { get; set; }
        public virtual DbSet<SmsReplyReport> SmsReplyReports { get; set; }
        public virtual DbSet<SmsSend> SmsSends { get; set; }
        public virtual DbSet<SmsSendHistory> SmsSendHistories { get; set; }
        public virtual DbSet<SmsSendSwitch> SmsSendSwitches { get; set; }
        public virtual DbSet<SmsSendTask> SmsSendTasks { get; set; }
        public virtual DbSet<SoftType> SoftTypes { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Survey> Surveys { get; set; }
        public virtual DbSet<SurveyRecord> SurveyRecords { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Temp_OnlineUser> Temp_OnlineUser { get; set; }
        public virtual DbSet<TempBusiness> TempBusinesses { get; set; }
        public virtual DbSet<TempBusinessKey> TempBusinessKeys { get; set; }
        public virtual DbSet<UpgradeNote> UpgradeNotes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserAgent> UserAgents { get; set; }
        public virtual DbSet<UserBusiness> UserBusinesses { get; set; }
        public virtual DbSet<UserGroup> UserGroups { get; set; }
        public virtual DbSet<WebAddValueNote> WebAddValueNotes { get; set; }
        public virtual DbSet<WeiXinConfig> WeiXinConfigs { get; set; }
        public virtual DbSet<WeiXinMapping> WeiXinMappings { get; set; }
        public virtual DbSet<WeixinMapping1> WeixinMappings1 { get; set; }
        public virtual DbSet<WeixinMessage> WeixinMessages { get; set; }
        public virtual DbSet<WeixinParameter> WeixinParameters { get; set; }
        public virtual DbSet<WeixinReplyNode> WeixinReplyNodes { get; set; }
        public virtual DbSet<WeiXinReplyRule> WeiXinReplyRules { get; set; }
        public virtual DbSet<WeixinUserMap> WeixinUserMaps { get; set; }
    }
}
