//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementDataModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OemParameter
    {
        public System.Guid Guid { get; set; }
        public Nullable<System.Guid> AgentGuid { get; set; }
        public byte[] SID { get; set; }
        public string LoginTitle { get; set; }
        public Nullable<bool> IsDisplaySetup { get; set; }
        public string LogoName { get; set; }
        public string LoginSkin { get; set; }
        public string LogoName2 { get; set; }
        public string EPosLaunchLogo { get; set; }
        public string EPosLoginLogo { get; set; }
        public string Copyright { get; set; }
    }
}
