//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementDataModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineUser
    {
        public System.Guid Guid { get; set; }
        public byte[] SID { get; set; }
        public string SessionId { get; set; }
        public string BusinessAccount { get; set; }
        public string BusinessName { get; set; }
        public string UserAccount { get; set; }
        public System.DateTime LoginTime { get; set; }
        public int LoginType { get; set; }
        public string LoginIP { get; set; }
        public string LatLong { get; set; }
        public System.Guid msrepl_tran_version { get; set; }
    }
}
