//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementDataModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public System.Guid Guid { get; set; }
        public byte[] SID { get; set; }
        public string OrderNo { get; set; }
        public int OrderType { get; set; }
        public decimal TotalMoney { get; set; }
        public int OrderState { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string CreateUserNo { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public string Modifier { get; set; }
        public Nullable<System.DateTime> CheckTime { get; set; }
        public string CheckUserNo { get; set; }
        public string Remark { get; set; }
        public string Contract { get; set; }
        public Nullable<decimal> TotalSoftMoney { get; set; }
        public Nullable<decimal> TotalHardWareMoney { get; set; }
        public Nullable<System.DateTime> ContractDate { get; set; }
        public System.Guid msrepl_tran_version { get; set; }
    }
}
