//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementDataModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmsSendSwitch
    {
        public System.Guid Guid { get; set; }
        public byte[] SID { get; set; }
        public string Mobile { get; set; }
        public string SmsContent { get; set; }
        public int SmsCount { get; set; }
        public int Status { get; set; }
        public string SendChanelKeyName { get; set; }
        public System.DateTime SendTime { get; set; }
        public int SendType { get; set; }
        public Nullable<System.DateTime> ReceiveTime { get; set; }
        public int Priority { get; set; }
        public string UserAccount { get; set; }
        public Nullable<System.Guid> ChainStoreGuid { get; set; }
        public string RelationKey { get; set; }
        public string Meno { get; set; }
        public bool IsFree { get; set; }
        public System.Guid msrepl_tran_version { get; set; }
    }
}
