//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementDataModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public System.Guid Guid { get; set; }
        public byte[] SID { get; set; }
        public string KeyName { get; set; }
        public int KeyType { get; set; }
        public decimal BasePrice { get; set; }
        public decimal BaseLicensePrice { get; set; }
        public decimal ServicePrice { get; set; }
        public bool IsServiceByLicense { get; set; }
        public int StatusFlag { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public bool IsStop { get; set; }
        public System.Guid msrepl_tran_version { get; set; }
        public decimal PerYearMoney { get; set; }
        public int UserCounts { get; set; }
        public decimal RenewalsPerYearMoney { get; set; }
        public double Discount { get; set; }
    }
}
