//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementDataModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp_OnlineUser
    {
        public System.Guid Guid { get; set; }
        public byte[] SID { get; set; }
        public string Account { get; set; }
        public string BusinessName { get; set; }
        public string IndustryName { get; set; }
        public string UserAccount { get; set; }
        public string StoreName { get; set; }
        public string Contact { get; set; }
        public string Tel { get; set; }
        public string LoginProvince { get; set; }
        public string LoginCity { get; set; }
        public string LoginCounty { get; set; }
        public string StoreProvince { get; set; }
        public string StoreCity { get; set; }
        public string StoreCounty { get; set; }
        public string StoreAddres { get; set; }
    }
}
