//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementDataModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebAddValueNote
    {
        public System.Guid Guid { get; set; }
        public string Transaction_id { get; set; }
        public string Bargainor_id { get; set; }
        public string Sp_billno { get; set; }
        public string Total_fee { get; set; }
        public string Bank_type { get; set; }
        public Nullable<int> Flag { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<System.DateTime> OperatetTime { get; set; }
        public string Meno { get; set; }
        public System.Guid msrepl_tran_version { get; set; }
    
        public virtual Business Business { get; set; }
    }
}
