//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementDataModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeixinReplyNode
    {
        public System.Guid Guid { get; set; }
        public Nullable<System.Guid> Parent { get; set; }
        public byte[] SID { get; set; }
        public int MessageMode { get; set; }
        public int ReplyType { get; set; }
        public string RegString { get; set; }
        public bool IsRegMode { get; set; }
        public int Sort { get; set; }
        public string WeixinMessageGuids { get; set; }
        public string NodeHandler { get; set; }
        public string Meno { get; set; }
        public bool IsEnable { get; set; }
        public System.Guid msrepl_tran_version { get; set; }
    }
}
